include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Light Control
LUCI_DEPENDS:=+luci-base +light_control
LUCI_PKGARCH:=all

PKG_LICENSE:=MIT
PKG_MAINTAINER:=xdcsystems

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
