#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1

start_service() {
    config_load light_control

    start_instance() {
        local enabled
        config_get_bool enabled "$1" enabled 1
        [ "$enabled" = 1 ] || return 0

        procd_open_instance
        procd_set_param command /usr/bin/light_control
        procd_set_param file /etc/config/light_control
        #procd_set_param respawn 3600 5 10
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_close_instance
    }

    config_foreach start_instance light_control
}

service_triggers() {
    procd_add_reload_trigger "light_control"
}

stop_service() {
    :
}